### ISSUE TITLE
User not created

### ISSUE THREAD

**Issue by motionthings** [imagegenius/docker-semaphore#1]
I'm trying to run semaphore through the unraid 'Community Applications' plugin.

I'm using the built in bolt db

![image](https://user-images.githubusercontent.com/264911/232341411-abdf9ae2-732e-45c8-88bb-23c8d011b900.png)

![image](https://user-images.githubusercontent.com/264911/232341703-99fe8974-a009-45f8-b7f0-5c732af2cf70.png)

Is the docker run command adding ' that should not be there?

**Comment by hydazz** [comment]
You need to tell it where the config is:

`semaphore user list --config /config/config.json`

**Comment by motionthings** [comment]
It's adding the user but I can not log in.

![image](https://user-images.githubusercontent.com/264911/232343510-cb5bf8c8-5871-4a12-b14c-6e7c43aa2a60.png)

![image](https://user-images.githubusercontent.com/264911/232343527-2e472e74-3e69-426e-9bf9-4441bf135aef.png)

I restarted the container

**Comment by hydazz** [comment]
strange, works for me
```
root@ee0a7c767b36:/# semaphore user add --name test --login test --email test@test.com --password test --config /config/config.json 
User test <test@test.com> added!
root@ee0a7c767b36:/# semaphore user get --login test --config /config/config.json 
ID: 2
Created: 2023-04-17 08:23:31 +0000 UTC
Login: test
Name: test
Email: test@test.com
Admin: false
root@ee0a7c767b36:/#
```
<img width="1512" alt="Screenshot 2023-04-17 at 8 24 41 am" src="https://user-images.githubusercontent.com/53986978/232346032-6301016f-8d27-487c-a882-10feb146eefb.png">

**Comment by motionthings** [comment]
I deleted the container and set it up again. It works now.
Only thing I did different was not using ! as the first character in my password.

Thank you for helping :)
