### ISSUE TITLE
Email not working

### ISSUE THREAD

**Issue by masterwishx** [imagegenius/docker-semaphore#10]
email not sending 
![image](https://github.com/user-attachments/assets/e2146a1b-6e2a-4d44-9806-82564fb1d0a6)

**Comment by hydazz** [comment]
How are you triggering the alert?

**Comment by masterwishx** [comment]
> How are you triggering the alert?

I set enable alert in admin and project

**Comment by masterwishx** [comment]
Also I think should work on success if not enabled (suppress on success) but I don't see even attempt in this case

**Comment by masterwishx** [comment]
port 587 is working instead of 465
