### ISSUE TITLE
Only two apps avalible ?

### ISSUE THREAD

**Issue by masterwishx** [imagegenius/docker-semaphore#11]
![image](https://github.com/user-attachments/assets/9b4e0860-75b4-4fb1-839f-0fb3b9a6c279)

**Comment by hydazz** [comment]
I haven't use the applications, are you expecting to see anything else?

**Comment by masterwishx** [comment]
> I haven't use the applications, are you expecting to see anything else?

After updated to lasted version you can enable the rest apps
