### ISSUE TITLE
Fresh install doesn't work

### ISSUE THREAD

**Issue by Axsgranted** [imagegenius/docker-semaphore#4]
Get the following error from the logs.  In the redacted section I put in my IP for unraid host. Changed no other variables.

goroutine 1 [running]:
github.com/ansible-semaphore/semaphore/db/bolt.(*BoltDb).Connect(0xc0001a18c0, {0xb9710b, 0x4})
        /go/src/github.com/ansible-semaphore/semaphore/db/bolt/BoltDb.go:110 +0x36d
github.com/ansible-semaphore/semaphore/cli/cmd.createStore({0xb9710b, 0x4})
        /go/src/github.com/ansible-semaphore/semaphore/cli/cmd/root.go:96 +0x65
github.com/ansible-semaphore/semaphore/cli/cmd.runService()
        /go/src/github.com/ansible-semaphore/semaphore/cli/cmd/root.go:43 +0x48
github.com/ansible-semaphore/semaphore/cli/cmd.glob..func3(0x25d2e60?, {0xb96f17?, 0x2?, 0x2?})
        /go/src/github.com/ansible-semaphore/semaphore/cli/cmd/server.go:18 +0x17
github.com/spf13/cobra.(*Command).execute(0x25d2e60, {0xc000090900, 0x2, 0x2})
        /go/src/github.com/ansible-semaphore/semaphore/vendor/github.com/spf13/cobra/command.go:860 +0x663
github.com/spf13/cobra.(*Command).ExecuteC(0x25d21e0)
        /go/src/github.com/ansible-semaphore/semaphore/vendor/github.com/spf13/cobra/command.go:974 +0x3b4
github.com/spf13/cobra.(*Command).Execute(...)
        /go/src/github.com/ansible-semaphore/semaphore/vendor/github.com/spf13/cobra/command.go:902
github.com/ansible-semaphore/semaphore/cli/cmd.Execute()
        /go/src/github.com/ansible-semaphore/semaphore/cli/cmd/root.go:36 +0x5b
main.main()
        /go/src/github.com/ansible-semaphore/semaphore/cli/main.go:8 +0x17
panic: open [redacted]: permission denied

**Comment by hydazz** [comment]
is `[redacted]` a path or ip?

**Comment by Axsgranted** [comment]
IP of the Unraid host

**Comment by hydazz** [comment]
there is no reason to redact a private IP, nevertheless, can you provide a screenshot of the template, or if you are using `SEMAPHORE_DB_DIALECT=bolt` then remove the variables that start with `SEMAPHORE_DB...` eg `SEMAPHORE_DB_HOST`

**Comment by Axsgranted** [comment]
Happy to debate the relevance of sharing internal network details externally attached to my known alias in another forum.  I did state in my original posting that it was an IP of the Unraid Host.

I removed the container and deleted the appdata folder for good measure to start over.  The variables I changed were the Admin Password, Name, email and Encryption (tried leaving this default as well, made no difference) and removed DB Host, Port, User, Pass and DB variables.  I also double checked, not that Unraid will let you, to ensure I'm not using port 3000 for the admin interface, anywhere else on my server.

The deployment log still shows your default variables in the log as it deploys and the site is still unresponsive after completing.

[https://i.imgur.com/KJJzSqa.png](url)
[https://i.imgur.com/qYr2NkW.png](url)

**Comment by Axsgranted** [comment]
I was able to deploy with no issue, outside of Unraid, following the Sempahore docker instructions:
[https://docs.ansible-semaphore.com/administration-guide/installation](url)

**Comment by hydazz** [comment]
They are being set as variables because you failed to remove them from the template, unraid will automatically set variables that are blank to the default unless they are removed with the `REMOVE` button

**Comment by Axsgranted** [comment]
> They are being set as variables because you failed to remove them from the template, unraid will automatically set variables that are blank to the default unless they are removed with the `REMOVE` button

Gotcha, thats helpful!
